### ISSUE TITLE
Broken link for apoplexy

### ISSUE THREAD

**Issue by uguu-org** [oklemenz/PrinceJS#11]
Current link for apoplexy is broken, the correct link is probably:

https://apoplexy.github.io/apoplexysite/

According to [archive.org](https://web.archive.org/web/20230205051530/http://apoplexy.org/), the domain was suspended due to some verification issue, and now it has been parked by a different operator.

Related: https://github.com/oklemenz/PrinceJS/issues/6

**Comment by oklemenz** [comment]
Fixed with #12
