### ISSUE TITLE
Remastered

### ISSUE THREAD

**Issue by VVL99** [oklemenz/PrinceJS#13]
Do you have any desire to make an HD version, with new textures and sound?

**Comment by oklemenz** [comment]
Not me. Feel free to fork this repo and provide an enhanced version including HD graphics. But as the point of this repo is to make the original game easy accessible to everyone, I currently will not invest in that.

**Comment by VVL99** [comment]
Thanks for your work.

**Comment by VVL99** [comment]
https://fastpic.org/fullview/80/2016/0810/6cc6b22a1a05e4254498c25ca989e611.jpg.html?r=1

https://vvl99.narod.ru/princejs/assets/sfx/34_Wind_and_Torch.mp3
https://vvl99.narod.ru/princejs/assets/sfx/35_Cave.mp3

**Comment by VVL99** [comment]
https://www.youtube.com/watch?v=eMG8YApA7nY&t=1s
