### ISSUE TITLE
Guards should not turn in your direction if you are walking cautiously

### ISSUE THREAD

**Issue by Oblomov** [oklemenz/PrinceJS#2]
There are a couple of instances where (at least in the DOS version that I remember) you could gain a few frame of motion against a guard by running to make them turn in your direction, and then walking cautiously until you got behind them. In seems that here guards are always turned towards you here instead.

**Comment by oklemenz** [comment]
Yes, that's not implemented. Guard always turn in Kid's direction if in sight. Do you have a concrete example I can check? Level, Room? That would help.

**Comment by Oblomov** [comment]
There's at least two I remember. The last guard in Level 2 is one example. [You can circumvent him](https://youtu.be/9a9H7UNXrLs?t=96) by going left at the indicated timestamp, but if you climb up instead you end right under him and should be able to “distract” him. Another is on Level 8, as shown at the 2:00 minute timestamp [in this video](https://youtu.be/IFoQyvJ3JnI?t=120). I don't remember others out of the top of my head.

**Comment by oklemenz** [comment]
Thanks for the example, I will check, if this can be done as well ...

**Comment by oklemenz** [comment]
I implemented sneaking up of guards. Please have a look. Thx for the hint...
