### ISSUE TITLE
Bogus guillotine collision ?

### ISSUE THREAD

**Issue by mnouquet** [oklemenz/PrinceJS#4]
There might be a bug in the display of the blood stains in the guillotine trap, cf. attached screenshot.

Already happened twice on level 122 (https://princejs.com/?level=122&health=10&time=59&strength=100&width=0), once in the previous guillotine, Prince was falling down after killing the guard and got it back "chopped off", and once here running through this guillotine, getting its back foot "chopped off" but not dying.

<img width="1440" alt="Screen Shot 2022-02-01 at 8 01 45 PM" src="https://user-images.githubusercontent.com/98864720/152091556-9b606ac8-b57e-445b-ab2b-52bec1b1c7ea.png">

**Comment by mnouquet** [comment]
Actually, I'm not entirely sure what's going on, something's very wrong with that current instance . Prince doesn't ever "fall"...

<img width="1440" alt="Screen Shot 2022-02-01 at 8 12 40 PM" src="https://user-images.githubusercontent.com/98864720/152092201-ed267f3b-dc07-4669-874c-cd4be0beb5e0.png">

This is happening on ```{
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
}```

**Comment by oklemenz** [comment]
Ok, I had a look. My Version is:
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36'

But I think it should not make a difference. I played the level 122 now again, and I cannot see those strange effects.

Can you reproduce it every time, or only randomly.

Please also be aware that all custom made levels (>=100) are not that good tested as the original ones... (most should work, but some have glitches)...

**Comment by mnouquet** [comment]
I'm playing ~every night (big THANKS to you btw!), this was a one-off issue.

**Comment by oklemenz** [comment]
Thanks a lot. Happy that someone also plays the custom levels. If it was an one-off, it's hard to reproduce. Therefore I close for now...

**Comment by mnouquet** [comment]
Actually, I just reproduced it. Consider the following screenshot:

![Screenshot_2022-02-04_15-21-33](https://user-images.githubusercontent.com/98864720/152616007-72c831ef-6761-44be-b823-083cca71b653.png)

Kill the guard, then climb on the upper left platform, jump on the upper right trigger, then have Prince walk carefully on the very lip of the trigger (shift-left), then press "Up". Prince will jump up then fall and get his butt chopped off, but not die. All the issues are there, he no longer fall either, spikes won't kill him, guards ignore him.

**Comment by mnouquet** [comment]
Btw, it's 100% reproducing now with the flow described (reproduced it another 2x time after my previous comment).

**Comment by oklemenz** [comment]
Cool, I will check it... Thanks

**Comment by oklemenz** [comment]
Thanks again for finding this issue. 

The coincidence, being chopped during free fall, lets him resurrect as Zombie Prince during landing... 🧟

I fixed this hidden feature 😀
