### ISSUE TITLE
No way to jump on computer

### ISSUE THREAD

**Issue by bibyts** [oklemenz/PrinceJS#5]
This is cool. Just played the new version but no way to jump on computer. https://princejs.com/

**Comment by oklemenz** [comment]
Which browser do you use? 
I tested it on Chrome and it works perfectly fine... 
Can you recheck?
Jumps are performed using the UP arrow key. In combination with LEFT/RIGHT you can jump across...

**Comment by oklemenz** [comment]
Jump is performed using cursor key "up"
