### ISSUE TITLE
https://www.apoplexy.org not reachable

### ISSUE THREAD

**Issue by Marietto2008** [oklemenz/PrinceJS#6]
I would like to visit this site,to give a look at how to do to create a custom level,but it is not reachable :

https://www.apoplexy.org

**Comment by oklemenz** [comment]
Site seems to be down currently. I think it will be up again soon. Until then you can download the software here:
https://www.popot.org/level_editors.php?editor=apoplexy

**Comment by Marietto2008** [comment]
I read that the instructional videos, can be found to : https://www.apoplexy.org ; but this site is down. Unfortunately I need of the tutorials. Do you have or can you put those videos (that I'm sure you have) in a different place ? Assuming that you can ask to the author if you can do it. let me know.

**Comment by oklemenz** [comment]
I think YouTube has those videos as well: https://youtu.be/wumqeXAv_Aw

Just Google for:

https://www.google.de/search?q=youtube+apoplexy+prince+of+persia+&client=safari&hl=de-de&ei=KrbaYv-OMLaE9u8P-7GCkAk&oq=youtube+apoplexy+prince+of+persia+&gs_lcp=ChNtb2JpbGUtZ3dzLXdpei1zZXJwEAM6BAgeEAo6BQghEKABSgUIQBIBMUoFCEASATFKBAhBGAFQvwpYvwpgqjRoAnAAeACAAdUBiAHsApIBBTAuMS4xmAEAoAEFoAEBwAEB&sclient=mobile-gws-wiz-serp#sbfbu=1&pi=youtube%20apoplexy%20prince%20of%20persia
