### ISSUE TITLE
Proposal : multiplayer version of Prince of Persia.

### ISSUE THREAD

**Issue by Marietto2008** [oklemenz/PrinceJS#7]
Hello.

I'm a system administrator. I have a decent knowledge on the management of Windows,Linux,FreeBSD,and so on. But I'm not a (web) programmer. But I really would like to add to "your" game,pop,the game that I liked more than any other game in my life,the multiplayer feature. Its very nice the idea to create a web server to play pop "online". But I'm very excited to the idea to see some of friend that he is playing pop like me and that I can fight against him to determine who will be able to save the princess before the time ends. Even more exciting is to see more friends playing the game,for a maximum of 10,for example,to riduce the lag time. To do this I have the will to learn the javascript and I'm looking for a good tutorial. If you can suggest me something,I will be happy. If you like my idea and you want to add it to pop,I'm happy,too. Otherwise,,maybe in 2 or 3 years you will see pop in multiplayer version. Do you want to contact me to talk about this project ? marietto2008@gmail.com. Very thanks.

**Comment by oklemenz** [comment]
There are plenty of good JavaScript resources. E.g. 

- https://www.w3schools.com/js/
- https://learnjavascript.online/

Also specifics of used game engine need to be learned: 

Phaser 2
- https://phaser.io/docs/2.6.2/index

I like the idea of multiplayer enabled Prince Of Persia. Feel free to add support for it.

Unfortunately, I currently have no resources to work on that. 

All the best.
