### ISSUE TITLE
Game immediately redirects me to the game over screen

### ISSUE THREAD

**Issue by DwayneJengSage** [oklemenz/PrinceJS#8]
I played PoP on prince.js for an hour. After my time ran out, the game sent me to the game over screen.

When I restarted, it dropped be back at Level 1, then immediately sent me to the game over screen again.

Refreshing the page didn't seem to help. Neither did manually filling in time=60 in the URL. Opening a private window also didn't help.

Does this game save state across runs? If so, how can I clear this state?

This also happened right as Daylight Savings changed over for me, if that makes a difference. Thanks!

**Comment by oklemenz** [comment]
Thanks for playing princejs. I cannot explain this behavior. No state is stored, except in the URL. So if you set "time=60" in a new tab, you should get the 60 minutes. Of course the internal computer clock is used to calculate the remaining time. In case DST switch was exactly to the time you played, the time passes too fast or even gives you time back, depending in which direction. But as this switch is exactly at midnight, opening a new browser tab with "princejs.com" should work normal again, as the start time is taken after the DST switch. I see nothing I could do here...
